### ISSUE TITLE
Error	CS1503	Argument 2: cannot convert from 'System.IO.FileMode' to 'Microsoft.WindowsAzure.Storage.AccessCondition'	

### ISSUE THREAD

**Issue by rhpoon** [Microsoft/StoreBroker#103]
Hi I am trying to access Azure Blob from the sample C# Console Application (for Retrain Azure Machine Learning Models Programmatically) and ran into this problem.

I am wondering if this is caused by the version of Azure Portal (maybe the codes are meant to access the classic Azure portal as indicated by Microsoft DOCs), or is caused by the package Microsoft.WindowsAzure.Storage (referenced to :\Users\user\source\repos\ConsoleApp1\packages\WindowsAzure.Storage.8.7.0\lib\net45\Microsoft.WindowsAzure.Storage.dll)

I have installed both: PM>  Install-Package Microsoft.AspNet.WebApi.Client and Install-Package WindowsAzure.Storage -Version 8.7.0 

 static void UploadFileToBlob(string inputFileLocation, string inputBlobName, string storageContainerName, string storageConnectionString)
        {
            // Make sure the file exists
            if (!File.Exists(inputFileLocation))
            {
                throw new FileNotFoundException(
                    string.Format(
                        CultureInfo.InvariantCulture,
                        "File {0} doesn't exist on local computer.",
                        inputFileLocation));
            }

            Console.WriteLine("Uploading the input to blob storage...");

            var blobClient = CloudStorageAccount.Parse(storageConnectionString).CreateCloudBlobClient();
            var container = blobClient.GetContainerReference(storageContainerName);
            container.CreateIfNotExists();
            var blob = container.GetBlockBlobReference(inputBlobName);
            blob.UploadFromFile(inputFileLocation, FileMode.Open);
        }

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'System.IO.FileMode' to 'Microsoft.WindowsAzure.Storage.AccessCondition'	ConsoleApp1	C:\Users\user\source\repos\ConsoleApp1\ConsoleApp1\Program.cs	116	Active

Any help or clues appreciated.

**Comment by HowardWolosky** [comment]
This doesn't appear to be a StoreBroker question.

This project is simply a consumer of Azure Data Movement, like yourself. If you have a question about using it, you may want to ask on the [actual project page](https://github.com/Azure/azure-storage-net-data-movement).

**Comment by HowardWolosky** [comment]
That being said, it looks like you're using a mismatched version of the package.  If you look at [our usage](https://github.com/Microsoft/StoreBroker/blob/master/StoreBroker/StoreIngestionApi.psm1), here are the versions we use:

      $nugetPackageName = "WindowsAzure.Storage"
      $nugetPackageVersion = "8.1.1"
      $assemblyPackageTailDir = "WindowsAzure.Storage.8.1.1\lib\net45\"
      $assemblyName = "Microsoft.WindowsAzure.Storage.dll"

      $nugetPackageName = "Microsoft.Azure.Storage.DataMovement"
      $nugetPackageVersion = "0.5.1"
      $assemblyPackageTailDir = "Microsoft.Azure.Storage.DataMovement.0.5.1\lib\net45\"
      $assemblyName = "Microsoft.WindowsAzure.Storage.DataMovement.dll"

And then the second parameter to your upload method would be the blob URL, not the file mode.
