### ISSUE TITLE
MSIX Packaging Support

### ISSUE THREAD

**Issue by drewkg** [Microsoft/StoreBroker#147]
With the change in the latest version of the Windows SDK 10.0.17763 the default packaging format for UWP Store submissions has changed from AppX to MSIX, are there plans to update the Store Broker scripts to support this packaging format along with the bundle and upload variants?

**Comment by HowardWolosky** [comment]
When I last spoke with the Store team, they weren't planning on supporting MSIX packages with the v1 API. I'll check back in with them again and reactivate this if the story has changed.
