### ISSUE TITLE
Recent Breaking Changes?

### ISSUE THREAD

**Issue by myokeeh** [microsoft/StoreBroker#174]
Was there a recent breaking change? I seem to get more failures with submissions using the API now.

> System.Exception: {"code":"InternalServerError","data":[],"details":[],"innererror":{"code":"UnknownInternalFailure","data":[],"details":[],"message":"The service has encountered an unknown 
internal server error: "},"message":"An internal server error occurred while processing the operation.","source":"Ingestion Api"}

**Comment by myokeeh** [comment]
Does it have something to do with the announcement below?

> Partner Security Requirements
Effective August 1, 2019, all partners are contractually required to enforce MFA for all tenant users and adopt the Secure Application Model when accessing Partner Center APIs. Non-compliance may result in your inability to transact and provide administrative services. Go here for more information.

https://partner.microsoft.com/resources/collection/partner-security-requirements#/

**Comment by HowardWolosky** [comment]
You would need to supply the MS-CorrelationId from your log file that correlates with the failure so that I can share with the API team to see if it is related or not.

**Comment by myokeeh** [comment]
@HowardWolosky I'm not sure I'm getting an ID with the sample C# code.

**Comment by HowardWolosky** [comment]
@myokeeh - I can't speak to the sample C# code, but StoreBroker will supply it in the Verbose output stream (and it's log file):

https://github.com/microsoft/StoreBroker/blob/345c521707a0bdbe5b72b8c512771c010d0b5cd4/StoreBroker/StoreIngestionApi.psm1#L1934-L1938

**Comment by myokeeh** [comment]
@HowardWolosky I'm not sure I'm getting anywhere with PowerShell/StoreBroker. Can you put me in touch with the Submission API team or let them know of the generic InternalServerError above?

**Comment by HowardWolosky** [comment]
@myokeeh - As I indicated, you need to provide a CorrelationID that is a header returned with your API request. StoreBroker includes that automatically in the Verbose stream and in the log file. If you're having trouble with StoreBroker specifically, please let me know what problem you're having. Without a CorrelationId, your issue is non-actionable by the API team.

**Comment by myokeeh** [comment]
I think my mistake is thinking the Submission API and StoreBroker teams are one. I don't use StoreBroker--having a hard time duplicating what I already have with the C# code on StoreBroker. I might attempt again later.

**Comment by HowardWolosky** [comment]
Correct. We are not related. I can forward support requests to them from here, but not without a CorrelationId.

**Comment by HowardWolosky** [comment]
Hi @myokeeh  - This issue is almost a year old.  Are you still blocked?

**Comment by myokeeh** [comment]
I honestly don't remember what happened. Maybe it was something expired that I renewed or it just started working again.
