### ISSUE TITLE
StoreBroker does not provide application package validation results

### ISSUE THREAD

**Issue by riverar** [microsoft/StoreBroker#181]
Windows 10 1909 18363.418
StoreBroker 1.19.1

When using `Update-ApplicationSubmission` to update a submission, with a to-be-uploaded package payload, there's no feedback as to whether or not the endpoint accepted the package. If the payload, for example, was corrupted, contained duplicate appx packages, etc. StoreBroker doesn't appear to report any errors.

This leads to some confusing files with a status of `PendingUpload`.

Suspect this is a v1 API issue?

**Comment by HowardWolosky** [comment]
Correct. With API v1, the only way to get this information is to keep querying the submission until its status changes. If it enters a failed state, the submission object will include the reason(s) for the failure. This is most easily achieved by using `Start-SubmissionMonitor`.
