### ISSUE TITLE
URLs to the dev portal with path dashboard/apps/ should be changed to dashboard/products

### ISSUE THREAD

**Issue by joseartrivera** [microsoft/StoreBroker#195]
The URL we are pointing users to in the below code snippet is incorrect, it should be changed to be `/dashboard/products/$appId/submissions`

https://github.com/microsoft/StoreBroker/blob/4d67f876fd7be0aade2143c5d95885970c8df915/StoreBroker/StoreIngestionApi.psm1#L1393

**Comment by HowardWolosky** [comment]
The correct link is `/dashboard/products/$appId/submissions`, and there are other similar links to be updated with different pathing throughout the module.

This would need to be fixed in both `master` (v1) and the `v2` branch.
