### ISSUE TITLE
Question: is there plan to have a GitHub Actions that will do a package update?

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/StoreBroker#196]
Hello,

GitHub Actions is getting some traction. Is there plan to have a GitHub Actions that would do the setup and offer the ability to update a package?

Thank you
Sébastien

**Comment by HowardWolosky** [comment]
Thanks for the suggestion.  I don't think that there's any current planned work around publishing our own action that will do that, however it _should_ be possible to author a custom action yourself that does that.

When working with v1, the complete set of commands necessary to perform a package update should be limited to:

```powershell
$secureString = ("<Your Access Token>" | ConvertTo-SecureString -AsPlainText -Force)  # Store <YourAccessToken> via an Action variable
$cred = New-Object System.Management.Automation.PSCredential "username is ignored", $secureString
Set-StoreBrokerAuthentication -Credential $cred

New-SubmissionPackage ...
Update-ApplicationSubmission ...
```

Really the only work involved is configuring the action to have your `AccessToken` and then properly pointing it to where your package is.

**Comment by ArchieCoder** [comment]
Yeah, doing the actual action is not an easy task. I'm in the C#/XAML world for so many years. Custom Actions are done in javascript I think.

Thanks for answering anyway!

**Comment by HowardWolosky** [comment]
@ArchieCoder -- a quick search came up with this link which seems to show it being quite simple to author a GitHub Action using PowerShell:  https://dfinke.github.io/powershell/2018/12/20/PowerShell-and-GitHub-Actions.html

If you just modify that `entrypoint.ps1` to instead have the code I referenced above, following their directions for securely configuring your `AccessToken` and adding in the necessary code to reference your binary package, I think it would be fairly straightforward to make it work.
