### ISSUE TITLE
Steps are missing to get the PDP files

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/StoreBroker#215]
Hi,

I followed the steps to install with PowerShellGallery. I was able to get the SBConfig file.

However, when I try the command: .\Extensions\ConvertFrom-ExistingSubmission.ps1 -AppId <appId> -Release <release> -PdpFileName <pdpFileName> -OutPath <outPath>

It says term is not found. I downloaded the files of the project on disk and tried to run the command without success
![image](https://user-images.githubusercontent.com/1608424/99582229-d08f4d00-29af-11eb-8b71-0cb4fb09fa5d.png)

What am I missing?
Thank you

**Comment by ArchieCoder** [comment]
Update: I was able to run the script without the parameter and the script asked for each parameter :)

**Comment by HowardWolosky** [comment]
I think it's the way that you've run the command.
You ran this:

```powershell
"ConvertFrom-ExistingSubmission.ps1" -AppId $appId -Release 2011 -PdpFileName PDP.xml -OutPath C:\PDP
```

I believe you need to do this:

```powershell
.\ConvertFrom-ExistingSubmission.ps1 -AppId $appId -Release 2011 -PdpFileName PDP.xml -OutPath C:\PDP
```
I've run it myself and verified that it runs just fine when using the above command.
