### ISSUE TITLE
msixupload bundle not supported by New-SubmissionPackage

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/StoreBroker#216]
Two weeks ago, we updated the minimum target version from 16299 to 17763 and Visual Studio is producing an .msixupload instead of .appxbundle. It looks like the tool is not happy about it.

![image](https://user-images.githubusercontent.com/1608424/99593750-2966e180-29c0-11eb-9bef-bba7dd9206a1.png)

However Partner Center accepts both formats
![image](https://user-images.githubusercontent.com/1608424/99594174-d17caa80-29c0-11eb-957e-612d3b063adf.png)

What can I do? Thanks

**Comment by LanceMcCarthy** [comment]
I reverted to appxupload for this reason. I'm curious what the plan is: fix this or just move on to V2?

Does the V2 API accept it? If yes, where can we find docs on migrating our V1 scripts to V2?

**Comment by HowardWolosky** [comment]
Per the Comment Based Help (which you can access by running `Get-Help New-SubmissionPackage -ShowWindow`), you need to be providing **full paths** to your appx files (e.g. `-AppxPath @('c:\PDP\App_4.2.121.0_x64_arm64_bundle.msixupload')`)

https://github.com/microsoft/StoreBroker/blob/93787985f7bd439721a26a552fa7f712e64471e6/StoreBroker/PackageTool.ps1#L3534-L3536

**Comment by HowardWolosky** [comment]
Correct that v1 of the API does not support `msix*` files however.  That is supported in v2, however v2 is not widely available for consumer usage at this time.

You can try modifying v1 to try supporting `msix*` extensions, but there's not guarantee that it will work...that's untested.  Here are the relevant changes from v2 that were done to support msix against the _v2_ api:

https://github.com/microsoft/StoreBroker/commit/d7d1a4c73b3f2ea5e3d414525da16e44fe4dc704
https://github.com/microsoft/StoreBroker/commit/bc7396f408a1a8fec1ef46c54a51cdefd3ff0467
https://github.com/microsoft/StoreBroker/commit/cf2379a8b6e60032f6c1fd1cd17ae27bd7b2318f

**Comment by HowardWolosky** [comment]
The simpler way to do the testing would be to just generate the Submission Package using your appxupload file.  Once it generates the zip and json, modify the json to reference the msixupload file instead, and then replace the appxupload with the msixupload in the zip.  At that point, you've created a submission package that uses the msixupload file...just try creating a submission update with it.  If it's successful, then we can look at making those change referenced above to v1.

**Comment by ArchieCoder** [comment]
I'm all new to this and basically just a C#/UWP dev. I would prefer to get back to appxbundle but I didn't see how to force this. There is no option for it.

![image](https://user-images.githubusercontent.com/1608424/99596941-2c180580-29c5-11eb-9c16-09f83df59efb.png)

**Comment by LanceMcCarthy** [comment]
To wrap up this thread, a public FYI

You can force the build to create an appx (or appxupload) by dropping the Minimum Target SDK to 16299. (you can keep the the Target SDK to the latest version).

In csproj/wapproj file:

![image](https://user-images.githubusercontent.com/3520532/99673680-16492580-2a43-11eb-8751-9dc7bd638185.png)

Or in Visual Studio Project > Settings UI:

![image](https://user-images.githubusercontent.com/3520532/99674322-e6e6e880-2a43-11eb-9775-d48937730dd1.png)

**Comment by HowardWolosky** [comment]
> To wrap up this thread, a public FYI

Thanks, @LanceMcCarthy!

Also -- for anyone that wants to try it, I've created a branch of v1 where `New-SubmissionPackage` supports `msix*` extensions:
https://github.com/HowardWolosky/StoreBroker/tree/v1MsixSupport

I haven't had the time to test to see what the API does if you try to submit an MSIX with it though with `Update-ApplicationSubmission`.  If someone is interested in trying that out and reporting back, that would be great.

**Comment by LanceMcCarthy** [comment]
I've downloaded the zip to try it on a clean machine. I already have the PS module installed on my existing boxes and don't want to take the chance on breaking any there (they're self-hosted agents & runners).

I think I will try it in Windows Sandbox with a locally built msixupload file.

**Comment by ArchieCoder** [comment]
I'm pleased to report that the branch https://github.com/HowardWolosky/StoreBroker/tree/v1MsixSupport works. I tested the certification and it passed. I see the uploaded package.

What do we go from here? Can this branch be merged? Thank you @HowardWolosky and @LanceMcCarthy

**Comment by HowardWolosky** [comment]
>I'm pleased to report that the branch https://github.com/HowardWolosky/StoreBroker/tree/v1MsixSupport works. I tested the certification and it passed. I see the uploaded package.

That's great news.  I'm pleasantly surprised to hear that msix* files _do_ work with API v1 after all, given what I had previously been told.

> What do we go from here? Can this branch be merged? 

I'll look into getting that merged-in this weekend and getting a new build pushed out to PowerShellGallery sometime in the next week.
