### ISSUE TITLE
Add support for downloading symbols from the Windows Developer Center

### ISSUE THREAD

**Issue by hig-dev** [microsoft/StoreBroker#218]
Hello,

I have published multiple UWP apps using the Windows Dev Center and for most of my apps I am using Microsoft AppCenter for diagnostics.
After every update of my apps, I have to manually go to https://partner.microsoft.com/en-us/dashboard/apps/APP-ID/managepackages for each of my apps and download the symbols. After that I can upload the symbols to AppCenter automatically using the AppCenter CLI.

The manual download of the symbols from the Windows Dev Center is a very tedious task, that should be possible to automate.
In your README you state that the StoreBroker should save developer time and decrease the friction with getting updates to the Windows Store and I think my suggestion aims to that goal.

I know that the Microsoft Store submission API doesn't support this feature yet, but I hope that you can reach to the responsible people in order to implement my suggestion.

Greetings,
Halil Göcer

**Comment by HowardWolosky** [comment]
Thanks for the suggestion, @hig-dev.  We have heard this request before, and I am aware of the value that it would provide.  API v1 (which is what StoreBroker v1 is targeted against) is a closed API.  No new additions are being made to it.  API v2 is in internal development preview (as is StoreBroker v2), but I will still pass along this feedback again for consideration into API v2.

There is no published timeframe for when API v2 (and thus StoreBroker v2) will be generally publicly available.
