### ISSUE TITLE
 New-SubmissionPackage - 'Envelope' time issue

### ISSUE THREAD

**Issue by ErwanJes** [microsoft/StoreBroker#219]
I am testing StoreBroker module since last week, the submission process seemed to work fine.
But today, I try to create a new package:
```
New-SubmissionPackage -ConfigPath "...SBConfig.json" -AppxPath "...appxupload" -OutPath ".\artifact\out" -OutName "package"
```

I'm getting a 400 error:
```
400 | 103: Field 'time' on type 'Envelope' is older than the allowed min date. Expected: now - 172800000ms, Actual: now - 519083031ms
Items Received: 1
Items Accepted: 0
Errors:
index statusCode message
----- ---------- -------
    0        400 103: Field 'time' on type 'Envelope' is older than the allowed min date. Expected: now - 172800000ms, Actual: now - 519083031ms
```

I don't have any 'Envelope' occurence in the config or PDP files

I'm using StoreBroker 1.21.0

**Comment by HowardWolosky** [comment]
That sounds like an error being surfaced by an underlying backend API that the Store Submission API depends on.
Does it still repro now?  If so, can you include more of the verbose log that occurs around that issue?  You can either see the verbose log by appending `-Verbose` to your command, or by opening up the `StoreBroker.log` file that is contained within your `Documents` folder.

**Comment by ErwanJes** [comment]
I relaunch the script and I am unable to reproduce this error :/
I don't think I changed something that could impact this error.

This is good news (I guess ;) )
