### ISSUE TITLE
Failed to commit after using Set-ApplicationSubmission

### ISSUE THREAD

**Issue by CheeryLee** [microsoft/StoreBroker#249]
Hi!

I'm trying to make a new submission via StoreBroker. Found the problem that any changes that provided with `Set-ApplicationSubmission` causes commit to fail in the end. It doesn't matter which property would be changed. It's enough to just run the command with the source submission object.

What I'm getting with Start-SubmissionMonitor:

```
Submission Status : CommitFailed

Status Details [Errors]                :
     code                  details
     ----                  -------
InvalidParameterValue Error. Request it is not IngestionWeb or IngestionApi. applicationId = <my app id>, submissionId = 1152921505697533853, The ClientIdentifier = IngestionAPIv1Worker
```

Steps to reproduce:
1. create new submission: `$sub = New-ApplicationSubmission -AppId <app_id>` 
2. run this **WITHOUT** changing anything in $sub object: `Set-ApplicationSubmission -AppId <app_id> -UpdatedSubmission $sub`
3. make a commit: `Complete-ApplicationSubmission -AppId <app_id> -SubmissionId ($sub.id)`
4. check the submission status using `Start-SubmissionMonitor`

I don't really understand what this error means. The code `InvalidParameterValue` usually tells us that something in the submission body is wrong, but details is completely useless unfortunately.

**Comment by MrCapitalQ** [comment]
I am also getting this error starting on March 15th. I can see the same error message when using the Get-ApplicationSubmission call to see why my submissions aren't going through. This happened once before that but went away by itself after a couple weeks. Both times, my usage of the StoreBroker did not change when this error started to occur so I'm thinking something changed server side? Not sure how to proceed here.

**Comment by JohanLorenzo** [comment]
Same here, we started seeing it on March 19th.

**Comment by HowardWolosky** [comment]
Thanks for the report everyone.  I was on vacation so my response was delayed.  I've reached out to the Store API team to let them know about the issue.  I'll report back here when I hear back from them.

**Comment by HowardWolosky** [comment]
The API team reports that they have deployed the fix, so things should be working again.  Closing this issue now.

**Comment by JohanLorenzo** [comment]
Thanks Howard! I confirm this works on my end 👍

**Comment by mkaply** [comment]
What was the issue?

**Comment by HowardWolosky** [comment]
> What was the issue?

Unfortunately, I don't have that info.  All I know is that they deployed an update to the API service backend to resolve it.
