### ISSUE TITLE
Publishing A Certified Submission Set To Manual Release

### ISSUE THREAD

**Issue by brianmichel** [microsoft/StoreBroker#270]
We're just starting to build automation to put out application into the store and I have submissions working that will automatically trigger certification, but I can't seem to find any function on StoreBroker that will let me publish a submission after it has been certified. Is this possible? Happy to just be pointed to some docs or code and I'll take it from there!

**Comment by HowardWolosky** [comment]
The v1 REST API does not have any support for that.  If you set the submission to be manual from the API, you need to actually publish it through the Portal (this is mentioned in the [StoreBroker docs here (look under `TargetPublishMode`)](https://github.com/microsoft/StoreBroker/blob/master/Documentation/USAGE.md#creating-a-new-application-submission)).
