### ISSUE TITLE
StoreBroker Submissions with Trailers are Hanging Forever in "Certification" Status

### ISSUE THREAD

**Issue by softworkz** [microsoft/StoreBroker#274]
Everything is looking fine. I've got the trailer in all PDP files like this:

![Image](https://github.com/user-attachments/assets/e77a135d-55d3-48d2-9c18-98a4bd79a6ce)

and StoreBroker correcty picks up the trailer file, puts it into the zip, just like all images. It also correctly uses the fallback language path (where the trailer is located) for all languages in the generated json file.

But when submitting with `-UpdateTrailers`, it hangs forever in "Certification" state (so yes, it passes "CommitStarted" and enters "Certification").

In the store portal it also shows that it's in certification. When I cancel certification and look at the submission, no errors are shown.
I can also see that the trailer is there for all languages (including title, thumb image and Xbox Hero image). 
The only thing that's missing is the dropdown value being set to show the trailer at the top, as reported here: https://github.com/microsoft/StoreBroker/issues/273 (but that shouldn't cause it to hang in certification)

If I make the same submission without specifying `-UpdateTrailers`, it's working and gets certified after 1.5-3h as usual.

How can I get this working, who is responsible, whom to contact?

Thanks

**Comment by softworkz** [comment]
Okay, I'll do that, thanks.

What's actually the status of the V2 API? Is this supposed to work (I'm only getting 403 errors). I'm confused, because the V3 versions of the DevOps tasks appear to be using StoreBroker V2 and everybody is struggling in getting it to work (https://github.com/microsoft/windows-dev-center-vsts-extension/issues/123)

**Comment by HowardWolosky** [comment]
> What's actually the status of the V2 API?

I've tried to answer that as best as I can in my response there: microsoft/windows-dev-center-vsts-extension#124

**Comment by softworkz** [comment]
Thanks a lot for that. I hope that these issues will help others to understand the situation.
(maybe you can pin this issue)

**Comment by softworkz** [comment]
> (maybe you can pin this issue)

Or even add a big note to the ReadMe about V2. It would have saved me a lot of time if I had known this.
