### ISSUE TITLE
503 - Service Unavailable when calling Get-Applications

### ISSUE THREAD

**Issue by martinsuchan** [Microsoft/StoreBroker#61]
This is probably not the best place, where to report it, but I'm getting this error whenever I try to connect to Windows Store submission API:
 > (503) Server Unavailable, Account service is experiencing issue. Please try again later.

Same happens when I try to connect to the backend manually in my test app.
Not sure, if this is just problem of my app, account or global, but in case it's global, any chance you could ping the right people that could fix it? Thanks!

**Comment by danbelcher-MSFT** [comment]
Hello Martin,

I've forwarded your issue on to the Submission API team and will let you know if they think there is an issue.  That said, I currently have no issues accessing the API and I haven't heard of other users seeing this issue.  I would double-check to see if you're authenticating correctly and that you're using the proper endpoints for your request.

Best of luck,
-Daniel Belcher

**Comment by danbelcher-MSFT** [comment]
Hello again,

Store API team said they have seen this issue from users whose AAD app was not onboarded to Dev Center.  They recommend you step through the prerequisites again.

https://docs.microsoft.com/en-us/windows/uwp/monetize/create-and-manage-submissions-using-windows-store-services#prerequisites
https://docs.microsoft.com/en-us/windows/uwp/monetize/create-and-manage-submissions-using-windows-store-services#associate-an-azure-ad-application-with-your-windows-dev-center-account

Best regards,
-Daniel Belcher

**Comment by martinsuchan** [comment]
Just an update, I've created new Azure AD app in Dev dashboard and it seems to work now.  
Anyway the server should definitely return better error code when the credentials are no longer valid, definitely not 5xx code which should be used only for server-side errors. Maybe **401 Unauthorized**?

**Comment by danbelcher-MSFT** [comment]
Martin, we've passed your feedback on to the API team.  Thank you for the help!

**Comment by tompesman** [comment]
Same problem, thanks for sharing your solution.
