### ISSUE TITLE
Submission fails if app has "priceId":"Base"

### ISSUE THREAD

**Issue by martinsuchan** [Microsoft/StoreBroker#68]
Just discovered this undocumented behavior of Dev Center API.
I have one app under my account that is Unavailable for anyone, only for testers with redeem code can get it.

![image](https://user-images.githubusercontent.com/3041397/31121134-4b19339a-a837-11e7-97b2-85bd616509c3.png)

If I query submission details for this app, the API returns for this submission **pricing->priceId=Base**. But When I try to update this submission and update for instance only the package, with the same pricing value, it ends on this error:
```
400 | Bad Request
The remote server returned an error: (400) Bad Request.
InvalidParameterValue : You must select a valid base price
MS-CorrelationId: 3e90dc80-cd4f-4ec9-a1eb-d99cf8e837ab
At C:\Users\marti\Documents\WindowsPowerShell\Modules\StoreBroker\StoreBroker\StoreIngestionApi.psm1:1984 char:9
```
It looks like Price Tier "Base" is not valid in the top "pricing", even though the Dev Center API returns it in this case. When I changed the priceId to "Free", submission update.
Expected behavior - if Dev Center API returns "priceId" : "Base" for any submission, it should accept it back when updating that submission without throwing errors.
  
Note, I know this is probably not the best place to report these types of errors. I've already tried to report several similar errors through the Dev Center Feedback form but with no success or answer. If you know better place where to report errors in the Dev Center APi, please, let me know!

**Comment by HowardWolosky** [comment]
Sorry that you're having this experience.  Thanks for the feedback.  I've sent it on to the Store API team and they are investigating.  Will write back when I have more to share.

**Comment by HowardWolosky** [comment]
@martinsuchan - quick update.

The Store team has identified the problem and is deploying a fix for this issue.  I'd imagine that it will no longer repro within the next couple days.

I've also asked them for clarification on the support process for the API (both in terms of the support channel and expected response time), given the experience you've described.  When I hear back from them, I'll re-open this with that additional detail.
